version: "3.9"
services:
  local-postgres:
    image: postgres
    restart: always
    container_name: local-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
